INSERT INTO albums (id, album_name, artist, genre, release_date, cover_url) VALUES
(1, 'OK Computer', 'Radiohead', 'Art Rock, Alternative Rock', '1997-05-21', 'https://upload.wikimedia.org/wikipedia/en/b/ba/Radioheadokcomputer.png'),
(2, 'To Pimp a Butterfly', 'Kendrick Lamar', 'Conscious Hip Hop, Jazz Rap', '2015-03-15', 'https://upload.wikimedia.org/wikipedia/en/f/f6/Kendrick_Lamar_-_To_Pimp_a_Butterfly.png'),
(3, 'Wish You Were Here', 'Pink Floyd', 'Progressive Rock, Art Rock', '1975-09-12', 'https://upload.wikimedia.org/wikipedia/en/a/a4/Wish_You_Were_Here_-_Front_Cover.lj.undated.jpg'),
(4, 'Kid A', 'Radiohead', 'Experimental Rock, Electronic', '2000-10-02', 'https://upload.wikimedia.org/wikipedia/en/a/a1/Radioheadkida.png'),
(5, 'The Dark Side of the Moon', 'Pink Floyd', 'Progressive Rock', '1973-03-01', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Dark_Side_of_the_Moon.png'),
(6, 'Abbey Road', 'The Beatles', 'Pop Rock, Art Rock', '1969-09-26', 'https://upload.wikimedia.org/wikipedia/en/4/42/Beatles_-_Abbey_Road.jpg'),
(7, 'Madvillainy', 'Madvillain', 'Abstract Hip Hop, Jazz Rap', '2004-03-23', 'https://upload.wikimedia.org/wikipedia/en/5/5e/Madvillainy_cover.png'),
(8, 'In the Court of the Crimson King', 'King Crimson', 'Progressive Rock, Art Rock', '1969-10-10', 'https://upload.wikimedia.org/wikipedia/en/8/84/In_the_Court_of_the_Crimson_King_-_1969.jpg'),
(9, 'Loveless', 'My Bloody Valentine', 'Shoegaze, Noise Pop', '1991-11-04', 'https://upload.wikimedia.org/wikipedia/en/e/e0/My_Bloody_Valentine_-_Loveless.png'),
(10, 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'David Bowie', 'Glam Rock, Art Rock', '1972-06-16', 'https://upload.wikimedia.org/wikipedia/en/0/01/ZiggyStardust.jpg'),
(11, 'The Velvet Underground & Nico', 'The Velvet Underground & Nico', 'Art Rock, Proto-Punk', '1967-03-12', 'https://upload.wikimedia.org/wikipedia/en/0/0c/Velvet_Underground_and_Nico.png'),
(12, 'good kid, m.A.A.d city', 'Kendrick Lamar', 'Conscious Hip Hop, West Coast Hip Hop', '2012-10-22', 'https://upload.wikimedia.org/wikipedia/en/2/22/Good_kid_maad_city_album_cover.jpg'),
(13, 'The Black Saint and the Sinner Lady', 'Charles Mingus', 'Avant-Garde Jazz, Third Stream', '1963-07-01', 'https://upload.wikimedia.org/wikipedia/en/e/e7/Black_Saint_and_the_Sinner_Lady.jpg'),
(14, 'Hounds of Love', 'Kate Bush', 'Art Pop, Progressive Pop', '1985-09-16', 'https://upload.wikimedia.org/wikipedia/en/2/23/Kate_Bush_-_Hounds_of_Love.png'),
(15, 'Highway 61 Revisited', 'Bob Dylan', 'Folk Rock, Singer-Songwriter', '1965-08-30', 'https://upload.wikimedia.org/wikipedia/en/9/95/Bob_Dylan_-_Highway_61_Revisited.jpg'),
(16, 'Revolver', 'The Beatles', 'Pop Rock, Psychedelic Rock', '1966-08-05', 'https://upload.wikimedia.org/wikipedia/en/1/16/Revolver_%28album_cover%29.jpg'),
(17, 'A Love Supreme', 'John Coltrane', 'Modal Jazz, Spiritual Jazz', '1965-02-01', 'https://upload.wikimedia.org/wikipedia/en/9/9a/John_Coltrane_-_A_Love_Supreme.jpg'),
(18, 'Spiderland', 'Slint', 'Post-Rock, Math Rock', '1991-03-27', 'https://upload.wikimedia.org/wikipedia/en/3/31/Slint_-_Spiderland.jpg'),
(19, 'Red', 'King Crimson', 'Progressive Rock, Art Rock', '1974-10-06', 'https://upload.wikimedia.org/wikipedia/en/8/8d/KingCrimsonRed.jpg'),
(20, 'Illmatic', 'Nas', 'East Coast Hip Hop, Boom Bap', '1994-04-19', 'https://upload.wikimedia.org/wikipedia/en/7/7b/NasIllmatic.jpg'),
(21, 'Remain in Light', 'Talking Heads', 'New Wave, Post-Punk', '1980-10-08', 'https://upload.wikimedia.org/wikipedia/en/3/37/TalkingHeadsRemainInLight.jpg'),
(22, 'In Rainbows', 'Radiohead', 'Art Rock, Alternative Rock', '2007-10-10', 'https://upload.wikimedia.org/wikipedia/en/1/14/Inrainbows_cover.png'),
(23, 'Lift Your Skinny Fists Like Antennas to Heaven', 'Godspeed You! Black Emperor', 'Post-Rock', '2000-10-09', 'https://upload.wikimedia.org/wikipedia/en/4/41/Lift_Your_Skinny_Fists_Like_Antennas_to_Heaven.jpg'),
(24, 'Unknown Pleasures', 'Joy Division', 'Post-Punk', '1979-06-15', 'https://upload.wikimedia.org/wikipedia/en/b/b7/UnknownPleasuresJoyDivision.org.jpg'),
(25, 'Animals', 'Pink Floyd', 'Progressive Rock, Art Rock', '1977-01-23', 'https://upload.wikimedia.org/wikipedia/en/7/70/PinkFloydAnimals2.jpg'),
(26, 'Songs in the Key of Life', 'Stevie Wonder', 'Soul, Funk', '1976-09-28', 'https://upload.wikimedia.org/wikipedia/en/e/e2/Songs_in_the_key_of_life.jpg'),
(27, 'The Blue Album', 'Weezer', 'Power Pop, Alternative Rock', '1994-05-10', 'https://upload.wikimedia.org/wikipedia/en/7/70/Weezer_-_Blue_Album.png'),
(28, 'Disintegration', 'The Cure', 'Gothic Rock, Post-Punk', '1989-05-02', 'https://upload.wikimedia.org/wikipedia/en/b/b8/The_Cure_-_Disintegration.png'),
(29, 'Pet Sounds', 'The Beach Boys', 'Baroque Pop, Progressive Pop', '1966-05-16', 'https://upload.wikimedia.org/wikipedia/en/b/bb/PetSoundsCover.jpg'),
(30, 'Voodoo', 'D''Angelo', 'Neo-Soul, R&B', '2000-01-25', 'https://upload.wikimedia.org/wikipedia/en/1/1a/DAngeloVoodoo.jpg'),
(31, 'Aquemini', 'OutKast', 'Southern Hip Hop, Conscious Hip Hop', '1998-09-29', 'https://upload.wikimedia.org/wikipedia/en/7/70/Aquemini.jpg'),
(32, 'Endtroducing.....', 'DJ Shadow', 'Instrumental Hip Hop, Trip Hop', '1996-09-16', 'https://upload.wikimedia.org/wikipedia/en/a/a2/DJ_Shadow_-_Endtroducing.....jpg'),
(33, 'Master of Puppets', 'Metallica', 'Thrash Metal', '1986-03-03', 'https://upload.wikimedia.org/wikipedia/en/5/5c/Metallica_-_Master_of_Puppets_cover.jpg'),
(34, 'Grace', 'Jeff Buckley', 'Alternative Rock, Singer-Songwriter', '1994-08-23', 'https://upload.wikimedia.org/wikipedia/en/b/be/Jeff_Buckley_grace.jpg'),
(35, 'Dummy', 'Portishead', 'Trip Hop', '1994-08-22', 'https://upload.wikimedia.org/wikipedia/en/7/77/Portishead_-_Dummy.png'),
(36, 'Is This It', 'The Strokes', 'Indie Rock, Garage Rock Revival', '2001-07-30', 'https://upload.wikimedia.org/wikipedia/en/0/09/The_Strokes_-_Is_This_It_cover.png'),
(37, 'Led Zeppelin [IV]', 'Led Zeppelin', 'Hard Rock, Blues Rock', '1971-11-08', 'https://upload.wikimedia.org/wikipedia/en/2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg'),
(38, 'Soundtracks for the Blind', 'Swans', 'Experimental Rock, Post-Rock', '1996-10-22', 'https://upload.wikimedia.org/wikipedia/en/f/f9/Swans_Soundtracks_for_the_Blind.jpg'),
(39, 'Electricladyland', 'The Jimi Hendrix Experience', 'Psychedelic Rock, Hard Rock', '1968-10-16', 'https://upload.wikimedia.org/wikipedia/en/e/e8/The_Jimi_Hendrix_Experience_-_Electric_Ladyland.jpg'),
(40, 'Demon Days', 'Gorillaz', 'Alternative Rock, Trip Hop', '2005-05-11', 'https://upload.wikimedia.org/wikipedia/en/d/d2/Gorillaz_Demon_Days.png'),
(41, 'Homogenic', 'Björk', 'Art Pop, Electronic', '1997-09-22', 'https://upload.wikimedia.org/wikipedia/en/a/af/Bj%C3%B6rk_-_Homogenic.png'),
(42, 'The Queen Is Dead', 'The Smiths', 'Jangle Pop, Indie Pop', '1986-06-16', 'https://upload.wikimedia.org/wikipedia/en/b/b2/The_Smiths_-_The_Queen_Is_Dead.png'),
(43, 'Blue', 'Joni Mitchell', 'Singer-Songwriter, Contemporary Folk', '1971-06-22', 'https://upload.wikimedia.org/wikipedia/en/7/70/Joni_Mitchell_-_Blue.jpg'),
(44, 'Kind of Blue', 'Miles Davis', 'Modal Jazz', '1959-08-17', 'https://upload.wikimedia.org/wikipedia/en/9/9c/MilesDavisKindofBlue.jpg'),
(45, 'In the Aeroplane Over the Sea', 'Neutral Milk Hotel', 'Indie Folk, Elephant 6', '1998-02-10', 'https://upload.wikimedia.org/wikipedia/en/7/73/In_the_aeroplane_over_the_sea_album_cover.png'),
(46, 'Violator', 'Depeche Mode', 'Synth-pop, Electronic', '1990-03-19', 'https://upload.wikimedia.org/wikipedia/en/9/91/Depeche_Mode_-_Violator.png'),
(47, 'Paranoid', 'Black Sabbath', 'Heavy Metal', '1970-09-18', 'https://upload.wikimedia.org/wikipedia/en/6/64/Black_Sabbath_-_Paranoid.jpg'),
(48, 'Nevermind', 'Nirvana', 'Grunge, Alternative Rock', '1991-09-24', 'https://upload.wikimedia.org/wikipedia/en/b/b7/NirvanaNevermindalbumcover.jpg'),
(49, 'Vespertine', 'Björk', 'Art Pop, Microhouse', '2001-08-27', 'https://upload.wikimedia.org/wikipedia/en/a/af/Bjork_Vespertine.png'),
(50, 'Blonde', 'Frank Ocean', 'Alternative R&B, Art Pop', '2016-08-20', 'https://upload.wikimedia.org/wikipedia/en/a/a0/Frank_Ocean_%20_Blonde.png'),
(51, 'Long Season', 'Fishmans', 'Dream Pop, Dub', '1996-10-25', 'https://upload.wikimedia.org/wikipedia/en/9/91/Fishmans_Long_Season.jpg'),
(52, 'The Low End Theory', 'A Tribe Called Quest', 'Conscious Hip Hop, Jazz Rap', '1991-09-24', 'https://upload.wikimedia.org/wikipedia/en/e/eb/ATribeCalledQuestTheLowEndTheory.jpg'),
(53, 'Crumbling', 'Mid-Air Thief', 'Neo-Psychedelia, Folktronica', '2018-06-30', 'https://upload.wikimedia.org/wikipedia/en/b/b0/Mid-Air_Thief_-_Crumbling.jpg'),
(54, 'Microphones in 2020', 'The Microphones', 'Indie Folk, Slowcore', '2020-08-07', 'https://upload.wikimedia.org/wikipedia/en/1/1a/Microphones_2020.png'),
(55, 'Selected Ambient Works 85-92', 'Aphex Twin', 'Ambient Techno, IDM', '1992-11-09', 'https://upload.wikimedia.org/wikipedia/en/d/d1/Selected_Ambient_Works_85-92.jpg'),
(56, 'Liquid Swords', 'GZA', 'East Coast Hip Hop, Hardcore Hip Hop', '1995-11-07', 'https://upload.wikimedia.org/wikipedia/en/2/21/GZA_-_Liquid_Swords.jpg'),
(57, 'Rumours', 'Fleetwood Mac', 'Soft Rock, Pop Rock', '1977-02-04', 'https://upload.wikimedia.org/wikipedia/en/f/fb/FMFleetwoodMacRumours.png'),
(58, 'London Calling', 'The Clash', 'Punk Rock, New Wave', '1979-12-14', 'https://upload.wikimedia.org/wikipedia/en/0/00/TheClashLondonCallingalbumcover.jpg'),
(59, 'Untrue', 'Burial', 'Future Garage, Dubstep', '2007-11-05', 'https://upload.wikimedia.org/wikipedia/en/2/23/Burial_Untrue.jpg'),
(60, 'Doolittle', 'Pixies', 'Indie Rock, Alternative Rock', '1989-04-17', 'https://upload.wikimedia.org/wikipedia/en/d/d7/Pixies-Doolittle.jpg'),
(61, 'Enter the Wu-Tang (36 Chambers)', 'Wu-Tang Clan', 'East Coast Hip Hop, Hardcore Hip Hop', '1993-11-09', 'https://upload.wikimedia.org/wikipedia/en/5/53/Wu-TangClanEntertheWu-Tang36Chambers.jpg'),
(62, 'Heaven or Las Vegas', 'Cocteau Twins', 'Dream Pop, Ethereal Wave', '1990-09-17', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Cocteau_Twins_-_Heaven_or_Las_Vegas.png'),
(63, 'What''s Going On', 'Marvin Gaye', 'Soul, Smooth Soul', '1971-05-21', 'https://upload.wikimedia.org/wikipedia/en/8/84/MarvinGayeWhat%27sGoingOn.jpg'),
(64, 'The Glow Pt. 2', 'The Microphones', 'Indie Folk, Lo-Fi', '2001-09-25', 'https://upload.wikimedia.org/wikipedia/en/7/7e/Microphonesglowpt2.jpg'),
(65, 'The Money Store', 'Death Grips', 'Experimental Hip Hop, Industrial Hip Hop', '2012-04-24', 'https://upload.wikimedia.org/wikipedia/en/6/69/Death_Grips_-_The_Money_Store.png'),
(66, 'Tapestry', 'Carole King', 'Singer-Songwriter, Soft Rock', '1971-02-10', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Carole_King_-_Tapestry.jpg'),
(67, 'Pink Moon', 'Nick Drake', 'Contemporary Folk, Singer-Songwriter', '1972-02-25', 'https://upload.wikimedia.org/wikipedia/en/b/b1/Nick_Drake_-_Pink_Moon.jpg'),
(68, 'Geogaddi', 'Boards of Canada', 'IDM, Ambient', '2002-02-18', 'https://upload.wikimedia.org/wikipedia/en/0/0a/BoardsofCanadaGeogaddi.jpg'),
(69, 'Close to the Edge', 'Yes', 'Progressive Rock', '1972-09-13', 'https://upload.wikimedia.org/wikipedia/en/1/12/Yes_-_Close_to_the_Edge.jpg'),
(70, 'Physical Graffiti', 'Led Zeppelin', 'Hard Rock, Blues Rock', '1975-02-24', 'https://upload.wikimedia.org/wikipedia/en/e/e3/Led_Zeppelin_-_Physical_Graffiti.jpg'),
(71, 'The Downward Spiral', 'Nine Inch Nails', 'Industrial Rock, Alternative Rock', '1994-03-08', 'https://upload.wikimedia.org/wikipedia/en/c/c0/Nine_Inch_Nails_-_The_Downward_Spiral.png'),
(72, 'Mezzanine', 'Massive Attack', 'Trip Hop, Dub', '1998-04-20', 'https://upload.wikimedia.org/wikipedia/en/3/3f/Massive_Attack_-_Mezzanine.png'),
(73, 'Alphaville', 'Imperial Triumphant', 'Avant-Garde Metal', '2020-07-31', 'https://upload.wikimedia.org/wikipedia/en/d/d8/Imperial_Triumphant_-_Alphaville.jpg'),
(74, 'Substrata', 'Biosphere', 'Ambient, Drone', '1997-07-28', 'https://upload.wikimedia.org/wikipedia/en/8/87/BiosphereSubstrata.jpg'),
(75, 'Symbolic', 'Death', 'Technical Death Metal', '1995-03-21', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Death_-_Symbolic.jpg'),
(76, 'To Be Kind', 'Swans', 'Experimental Rock, Post-Rock', '2014-05-12', 'https://upload.wikimedia.org/wikipedia/en/d/d8/Swans_ToBeKind.jpg'),
(77, 'Channel Orange', 'Frank Ocean', 'Alternative R&B, Neo-Soul', '2012-07-10', 'https://upload.wikimedia.org/wikipedia/en/2/28/Channel_ORANGE.jpg'),
(78, 'Bish Bosch', 'Scott Walker', 'Avant-Garde, Experimental', '2012-12-03', 'https://upload.wikimedia.org/wikipedia/en/c/c2/Scott_Walker_-_Bish_Bosch.jpg'),
(79, 'The Wall', 'Pink Floyd', 'Progressive Rock, Art Rock', '1979-11-30', 'https://upload.wikimedia.org/wikipedia/en/d/d6/PinkFloydWallCoverOriginalNoText.org.jpg'),
(80, 'Discovery', 'Daft Punk', 'French House, Synthpop', '2001-03-12', 'https://upload.wikimedia.org/wikipedia/en/a/ae/Daft_Punk_-_Discovery.png'),
(81, 'Mellon Collie and the Infinite Sadness', 'The Smashing Pumpkins', 'Alternative Rock', '1995-10-24', 'https://upload.wikimedia.org/wikipedia/en/2/27/SmashingPumpkins-MellonCollieAndTheInfiniteSadness.jpg'),
(82, 'In the Flat Field', 'Bauhaus', 'Gothic Rock, Post-Punk', '1980-11-03', 'https://upload.wikimedia.org/wikipedia/en/9/90/BauhausInTheFlatField.jpg'),
(83, 'Music Has the Right to Children', 'Boards of Canada', 'IDM, Ambient', '1998-04-20', 'https://upload.wikimedia.org/wikipedia/en/b/b4/MusicHasTheRightToChildren.jpg'),
(84, 'Souvlaki', 'Slowdive', 'Shoegaze, Dream Pop', '1993-05-17', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Slowdive_-_Souvlaki.png'),
(85, 'Ride the Lightning', 'Metallica', 'Thrash Metal', '1984-07-27', 'https://upload.wikimedia.org/wikipedia/en/e/e4/Metallica_-_Ride_the_Lightning_cover.jpg'),
(86, 'Blood on the Tracks', 'Bob Dylan', 'Singer-Songwriter, Folk Rock', '1975-01-20', 'https://upload.wikimedia.org/wikipedia/en/2/24/Bob_Dylan_-_Blood_on_the_Tracks.jpg'),
(87, 'Sign O'' the Times', 'Prince', 'Funk, Pop Rock', '1987-03-30', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Prince_-_Sign_o%27_the_Times.png'),
(88, 'Apostrophe ('')', 'Frank Zappa', 'Experimental Rock, Jazz Rock', '1974-04-22', 'https://upload.wikimedia.org/wikipedia/en/c/c8/Apostrophe.jpg'),
(89, 'The Idiot', 'Iggy Pop', 'Art Rock, Post-Punk', '1977-03-18', 'https://upload.wikimedia.org/wikipedia/en/a/a6/Iggy_Pop_-_The_Idiot.jpg'),
(90, 'Lateralus', 'Tool', 'Progressive Metal, Alternative Metal', '2001-05-15', 'https://upload.wikimedia.org/wikipedia/en/8/82/Tool_-_Lateralus.jpg'),
(91, 'Pornography', 'The Cure', 'Gothic Rock, Post-Punk', '1982-05-04', 'https://upload.wikimedia.org/wikipedia/en/a/a1/The_Cure_-_Pornography.png'),
(92, 'Hunky Dory', 'David Bowie', 'Art Pop, Glam Rock', '1971-12-17', 'https://upload.wikimedia.org/wikipedia/en/8/82/DavidBowieHunkyDory.jpg'),
(93, 'Marquee Moon', 'Television', 'Post-Punk, Art Punk', '1977-02-08', 'https://upload.wikimedia.org/wikipedia/en/b/b8/TelevisionMarqueeMoon.jpg'),
(94, 'Plastic Ono Band', 'John Lennon', 'Singer-Songwriter, Pop Rock', '1970-12-11', 'https://upload.wikimedia.org/wikipedia/en/c/c3/JohnLennonPlasticOnoBand.jpg'),
(95, 'Grace and Danger', 'John Martyn', 'Folk Rock, Singer-Songwriter', '1980-10-01', 'https://upload.wikimedia.org/wikipedia/en/e/e9/John_Martyn_-_Grace_and_Danger.jpg'),
(96, 'The Suburbs', 'Arcade Fire', 'Indie Rock, Art Rock', '2010-08-02', 'https://upload.wikimedia.org/wikipedia/en/1/1d/Arcade_fire_suburbs_cover.jpg'),
(97, 'Toxicity', 'System of a Down', 'Alternative Metal, Nu Metal', '2001-09-04', 'https://upload.wikimedia.org/wikipedia/en/6/63/SystemofadownToxicity.jpg'),
(98, 'Bridges to Babylon', 'The Rolling Stones', 'Pop Rock, Classic Rock', '1997-09-29', 'https://upload.wikimedia.org/wikipedia/en/5/52/Rolling_Stones_-_Bridges_to_Babylon.jpg'),
(99, 'Yeti', 'Amon Düül II', 'Krautrock, Psychedelic Rock', '1970-03-01', 'https://upload.wikimedia.org/wikipedia/en/f/f6/Yeti_Amon_Duul.jpg'),
(100, 'Karma', 'Pharoah Sanders', 'Spiritual Jazz, Free Jazz', '1969-05-01', 'https://upload.wikimedia.org/wikipedia/en/c/c8/Karma_Pharoah_Sanders.jpg');