spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5433/library
spring.datasource.username=postgres
spring.datasource.password=190111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true